In [24]:
import pandas as pd
import powerplantmatching as pm
import unidecode

In [25]:
print(pm.__version__)

_orig_unidecode = unidecode.unidecode

def safe_unidecode(x):
    if pd.isna(x):
        return ""
    return _orig_unidecode(str(x))

unidecode.unidecode = safe_unidecode

geo = pm.data.GEO()

0.8.0

/home/tom/miniconda3/envs/IES/lib/python3.13/site-packages/powerplantmatching/cleaning.py:255: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  return df.assign(**cols)

RecursionError: maximum recursion depth exceeded

In [ ]:
nl = geo[geo["Country"] == "Netherlands"]
nl.head()

In [ ]:
nl.powerplant.plot_map(figsize=(11, 8));

In [26]:
nl.powerplant.lookup().head(20).to_frame()

                          Capacity
Country     Fueltype
Netherlands Hard Coal     6955.092
            Natural Gas  14040.822
            Nuclear        458.027
            Oil            324.217
            Waste          238.383
            Wind             0.000

In [27]:
nl.powerplant.fill_missing_commissioning_years().head()

GEO,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
454,Gelderland Coal Netherlands 1,Hard Coal,NaN,PP,Netherlands,543.942804,NaN,1981.0,1985.0,NaN,51.8561,5.8294,NaN,NaN,NaN,NaN,NaN,GEO-44518
455,Eemshaven Usc Coal Netherlands 1,Hard Coal,NaN,PP,Netherlands,737.549565,NaN,2014.0,2014.0,NaN,53.4441,6.8560,NaN,NaN,NaN,NaN,NaN,GEO-44523
456,Eemshaven Usc Coal Netherlands 2,Hard Coal,NaN,PP,Netherlands,737.549565,NaN,2014.0,2014.0,NaN,53.4441,6.8560,NaN,NaN,NaN,NaN,NaN,GEO-44523
457,Amer Chp Coal Netherlands 1,Hard Coal,CCGT,CHP,Netherlands,594.649337,NaN,1980.0,1980.0,NaN,51.7081,4.8438,NaN,NaN,NaN,NaN,NaN,GEO-44517
458,Amer Chp Coal Netherlands 2,Hard Coal,CCGT,CHP,Netherlands,553.162174,NaN,1993.0,1993.0,NaN,51.7081,4.8438,NaN,NaN,NaN,NaN,NaN,GEO-44517

In [28]:
stats = pm.data.Capacity_stats()

In [30]:
entsoe = pm.data.ENTSOE()

entsoe.head()

pm.plot.fueltype_totals_bar([geo, entsoe, stats], keys=["ENTSOE", "GEO", "Statistics"]);

RecursionError: maximum recursion depth exceeded

In [31]:
dfs = [nl.powerplant.aggregate_units(), entsoe.powerplant.aggregate_units()]
intersection = pm.matching.combine_multiple_datasets(dfs)

RecursionError: maximum recursion depth exceeded